@startuml diagram1

actor ユーザー as a1
boundary 検索トップ画面 as b1
control 検索トップ画面表示 as c1
boundary チェックリスト画面 as d1
control チェックリスト画面表示 as e1 
entity 検索トップシステム as f1

c1 -> f1: 1:検索トップ画面情報を取得する
c1 <-- f1:
b1 <- c1: 1.1:検索トップ画面を表示する
a1 -> b1: 1.2:日本地図から地方をクリックする
b1 -> c1: 1.3:都道府県のラジオボタンを表示する
b1 <-- c1:
a1 -> b1: 1.4:都道府県のラジオボタンをクリックする
b1 -> c1: 1.5:都道府県のラジオボタンがチェックされた\n状態を表示する
b1 <-- c1:
a1 -> b1: 1.6:予定期間の初日をクリックする
b1 -> c1: 1.7:選択されたカレンダーを表示する
alt １日の場合
b1 <-- c1:1日選択されたカレンダーを表示する
a1 -> b1: 検索をクリックする
else それ以外の場合
a1 -> b1: 予定期間の最終日をクリックする
b1 -> c1: 初日から最終日まで選択されたカレンダーを表示する
b1 <-- c1:
end



a1 -> b1: 1.8:検索をクリックする
alt 正常に検索できた場合

b1 -> e1:チェックリスト画面を表示する
d1 <-- e1:
b1 -> c1:[旅行先、旅行期間の両方が選択されてない、\nまたは片方が選択されていない状態で\n「検索」をクリックされた場合]\n「行く予定の場所と日程を選択してください」と表示する
b1 <-- c1
end

@enduml
